### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by RazenHD** [AerWyn81/HeadBlocks#3] opened 2021-11-23 17:46 UTC
Hello there!

Having a problem: API's aren't working:

![image](https://user-images.githubusercontent.com/94925919/143077122-b01a5e54-ad05-4e88-aee8-47ae512c8323.png)
![image](https://user-images.githubusercontent.com/94925919/143077153-e7b8a0b0-c008-4d11-8ed4-46295829eca2.png)

**Comment by AerWyn81** [comment] 2021-11-23 18:08
Hi,

I'm going to look at this,

- Do you have any error in server startup log ?
- Do you have the line `[PlaceholderAPI] Successfully registered expansion: headblocks`
- Try to provide me some log, because I do not reproduce the problem (server version, plugins)

Sorry for the inconvenience,
Thanks for the report! ❤️

**Comment by AerWyn81** [comment] 2021-11-23 19:43
It seems that I am not interpreting the PAPI placeholders in the messages.

Why did you change the default message to include these placeholders? 
Why not use %current%/%max% as the default message?

![](https://i.imgur.com/63ERN9K.png)

**Comment by RazenHD** [comment] 2021-11-23 19:57
Because those placeholders arent listed here:

Also: using /hb me works with default API,
![image](https://user-images.githubusercontent.com/94925919/143094697-bdeaf8c4-c767-488d-8f34-3ea0b5cf8721.png)
using it here doesnt:
![image](https://user-images.githubusercontent.com/94925919/143094741-79580da1-8bef-4de1-a07a-ba9e3fbd9a4c.png)

Will look at the logs in a second. Thanks for the quick answer tho!

**Comment by AerWyn81** [comment] 2021-11-23 20:02
Yep, `%current%` & `%max%`  are specially dedicated for the /me command. 
They are not general placeholders (as are `%headblocks_current%` & `%headblocks_max%`)

I will still try to clarify and allow to use general placeholders everywhere

**Comment by RazenHD** [comment] 2021-11-23 20:02
[latest.log](https://github.com/AerWyn81/HeadBlocks/files/7590730/latest.log)

Doesn't say, that headblocks was registered.

**Comment by AerWyn81** [comment] 2021-11-23 20:05
In your logs : 
`[20:58:40] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: headblocks`
Looks good to me for HeadBlocks

But I see that there is a big error when PlaceholderAPI is starting :
`[20:58:49] [Server thread/ERROR]: [PlaceholderAPI] java.lang.NullPointerException: The expansion version is null!`

**Comment by RazenHD** [comment] 2021-11-23 20:06
> In your logs : `[20:58:40] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: headblocks` Looks good to me for HeadBlocks
> 
> But I see that there is a big error when PlaceholderAPI is starting : `[20:58:49] [Server thread/ERROR]: [PlaceholderAPI] java.lang.NullPointerException: The expansion version is null!`

Oh, Ctrl+F didn't show that for me somehow.

Do you maybe know what is causing this error?

**Comment by AerWyn81** [comment] 2021-11-23 20:10
Haha nice!

Yup, the line just above : 
`Failed to load expansion class ScoreboardTagsExpansion - One of its properties is null which is not allowed!`
It seems that there is a problem with ScoreboardTagsExpansion

**Comment by AerWyn81** [comment] 2021-11-23 20:27
You can try to unload ScoreboardTagsExpansion with `/papi unregister ScoreboardTagsExpansion` and try to restart the server to see if the issue is solve. It seems that there is an error with this expansion

**Comment by RazenHD** [comment] 2021-11-23 20:34
Apparently I dont have an Expansion called "ScoreboardTagsExpansion" or "ScoreboardTags". I just took it out of the Expansion folder and it still doesnt work
![image](https://user-images.githubusercontent.com/94925919/143100899-25e27f16-b070-451e-ad41-60c16a22d756.png)
[latest.log](https://github.com/AerWyn81/HeadBlocks/files/7590874/latest.log)
I dont see an error in the logs neither

**Comment by AerWyn81** [comment] 2021-11-23 20:41
Okey nice for that error.

Headblocks is well registered with PlaceholderAPI theres no issue.

If you want to use the placeholders `%headblocks_current%` and `%headblocks_max%` in /me command, I have to modify some code to allow that. I'll work on that for tomorrow. 
Meanwhile you can temporarily use `%current%` and `%max%` as placeholders for the /me command.

**Comment by RazenHD** [comment] 2021-11-23 20:43
Oh yea I got that!
The error now is, that this message is not /hb me
This message appears, when collecting an hb for the first time, so I want to let the players see how many they already collected and how many there are.
But apparently it doesn't work.

**Comment by AerWyn81** [comment] 2021-11-23 20:45
Aaaaah my bad, sorry I misunderstood! 
Ok well this will be part of my fix tomorrow, I have a bit of pro work, so I can't do this right away :/

**Comment by RazenHD** [comment] 2021-11-23 20:46
Alright!
I will let you know if I come across any other errors (hopefully not)
Keep up the work and thanks for the fast replies, really good support :)

Have a nice day then!

**Comment by AerWyn81** [comment] 2021-11-24 19:04
Hey,

The plugin has been updated with the fix for your need!
Don't hesitate to come back to me if you have any problem :)

https://www.spigotmc.org/resources/headblocks-1-8-1-17.97630/update?update=432140

**Closed by AerWyn81** 2021-11-24 19:04 UTC

**Comment by RazenHD** [comment] 2021-11-25 17:27
Just downloaded it and it works!
![image](https://user-images.githubusercontent.com/94925919/143482749-ca425dd7-ccf2-4133-a4fb-3c8649378eaa.png)

Thank you very much :)

**Comment by RazenHD** [comment] 2021-11-25 17:50
There's only one thing I don't really understand:
![image](https://user-images.githubusercontent.com/94925919/143484909-82d8431f-72ac-487d-8928-03cf9b66b6a2.png)

Shouldn't it say the message in chat, when having collected 2, or did I mess something up?

**Comment by AerWyn81** [comment] 2021-11-25 18:17
Hi,

Yep it should broadcast a message in your case.
I changed a bit the config when solving your issue, you don't need anymore to have the "cmd:" or "msg:" in the line

**Comment by RazenHD** [comment] 2021-11-25 18:25
Alright, changed it and it works!

Thank you
